language: node_js

node_js:
    - "stable"
    - "10"
    - "8"
    - "6"
    - "5"
    - "4"

notifications:
    email: false

before_script: npm install

after_success: npm run coverage

branches:
  only:
    - master
    - /^v[0-9].*$/
